--Automatizando seleção de colunas
select ',p_'||column_name||' loc_veiculo.' || column_name ||'%type'
  from user_tab_clumns
where table_name ='LOC_VEICULO' order by column_id;


--Autonomous Transaction, uso em LOG

--Criando a Tabela de LOG
CREATE TABLE LOG2017_2TDSR
(
  ID_SEQ NUMBER PRIMARY KEY,
  OSUSER VARCHAR2(1000),
  DT_EVENTO DATE,
  TXT VARCHAR(4000)
);

--Criando uma SEQ para PK
CREATE SEQUENCE SEQ_LOG2017_2TDSR START WITH 1 NOCACHE;

--Selecionando o Usuário do Computador
SELECT SYS_CONTEXT('USERENV','OS_USER') FROM DUAL;

--Criando a Procedure
CREATE OR REPLACE PROCEDURE PRC_LOG2017_2TDSR(
  P_OSUSER LOG2017_2TDSR.OSUSER%TYPE,
  P_DT_EVENTO LOG2017_2TDSR.DT_EVENTO%TYPE,
  P_TXT LOG2017_2TDSR.TXT%TYPE)
IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO LOG2017_2TDSR(ID_SEQ,OSUSER,DT_EVENTO,TXT)
  VALUES(SEQ_LOG2017_2TDSR.NEXTVAL,P_OSUSER,P_DT_EVENTO,P_TXT);
  COMMIT;
END;

--Rodando a Procedure
BEGIN
  PRC_LOG2017_2TDSR(SYS_CONTEXT('USERENV','OS_USER'),sysdate,'LOG INSERIDO ATRAVÉS DA PROCEDURE');
  ROLLBACK;
END;

--Adaptando Exercício da aula 2 para usar Autonomous Transaction.
create or replace PROCEDURE "PRC_INSERE_VEICULO"(
VNR_PLACA         LOC_VEICULO.NR_PLACA%TYPE,
VCD_PROPRIETARIO  LOC_VEICULO.CD_PROPRIETARIO%TYPE,
VSTATUS           LOC_VEICULO.STATUS%TYPE,
VCD_GRUPO          LOC_VEICULO.CD_GRUPO%TYPE)
IS
BEGIN
INSERT INTO LOC_VEICULO(NR_PLACA, CD_PROPRIETARIO, STATUS,CD_GRUPO)
VALUES(VNR_PLACA, VCD_PROPRIETARIO,VSTATUS,VCD_GRUPO);
COMMIT;
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
    PRC_LOG2017_2TDSR(SYS_CONTEXT('USERENV','OS_USER'),sysdate,'Erro ao inserir veículo! Chave '||VNR_PLACA||' JÁ EXISTE NA BASE DE DADOS');
    rollback;
		RAISE_APPLICATION_ERROR(-20001,'Placa já existe');
	WHEN INVALID_NUMBER THEN
		RAISE_APPLICATION_ERROR(-20002,'Número Inválido');
	WHEN VALUE_ERROR THEN
		RAISE_APPLICATION_ERROR(-20003,'Valor Inválido');
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR(-20004,'Erro Inesperado.'||sqlerrm);
END;

execute PRC_INSERE_VEICULO('ABC0987',1,'A',3);