--EXEMPLO 1
DECLARE
  V_IDADE NUMBER;
BEGIN
  V_IDADE := 'ZZZZZ';
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20001,'Erro Desconhecido =>' || sqlerrm);
END;

--EXEMPLO 2
DECLARE
  V_NUMERO_PAR NUMBER;
  V_ERRO_NUMERO_PAR EXCEPTION;
BEGIN
  FOR X IN 1..10 LOOP
    BEGIN
      IF MOD(X,2)=0 THEN
        RAISE V_ERRO_NUMERO_PAR;
      END IF;
    EXCEPTION
      WHEN V_ERRO_NUMERO_PAR THEN
        DBMS_OUTPUT.PUT_LINE(X|| ' É PAR');
       -- RAISE_APPLICATION_ERROR(-20999, 'Erro de Negócio'); Escalonamento de Exception
    END;
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20001, 'ABORTOU O PROGRAMA PELO ERRO ' || SQLCODE);
END;

--EXERCÍCIO
SELECT * FROM LOC_GRUPO;

CREATE TABLE LOC_GRUPO_EXCEPTION(
  CD_GRUPO            NUMBER(3) PRIMARY KEY,
  DS_GRUPO            VARCHAR2(100),
  VL_LOCACAO_DIARIA   NUMBER(8,2)); 

DECLARE
  CURSOR C_LOC_GRUPO IS
    SELECT * FROM PF0064.LOC_GRUPO;
  V_LOC_GRUPO C_LOC_GRUPO%ROWTYPE;
BEGIN
  OPEN C_LOC_GRUPO;
  LOOP
    BEGIN
      FETCH C_LOC_GRUPO INTO V_LOC_GRUPO;
        EXIT WHEN C_LOC_GRUPO%NOTFOUND;
    
      INSERT INTO LOC_GRUPO
      VALUES(V_LOC_GRUPO.CD_GRUPO,
        V_LOC_GRUPO.DS_GRUPO,
        V_LOC_GRUPO.VL_LOCACAO_DIARIA);
    EXCEPTION
      WHEN DUP_VAL_ON_INDEX THEN
        UPDATE LOC_GRUPO
        SET DS_GRUPO = V_LOC_GRUPO.DS_GRUPO,
          VL_LOCACAO_DIARIA = V_LOC_GRUPO.VL_LOCACAO_DIARIA
        WHERE CD_GRUPO = V_LOC_GRUPO.CD_GRUPO; 
    END;
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20001, 'ERRO DESCONHECIDO ' || SQLCODE);
END;

--TESTE EXERCÍCIO
SELECT * FROM loc_grupo;

SELECT COUNT(*) FROM LOC_GRUPO
MINUS
SELECT COUNT(*) FROM PF0064.LOC_GRUPO;