--USUARIOS ATIVOS
CREATE OR REPLACE VIEW VW_USUARIO_ATIVO AS
( SELECT IDN AS COD_FUNC
        ,NOME
        ,DOC_IDENTIFICACAO
    FROM TAB_FUNCIONARIO
   WHERE DT_DEMISSAO IS NULL 
);

--TOTAL GASTO EM SALARIOS
CREATE OR REPLACE VIEW VW_TOTAL_SALARIO AS
( SELECT SUM(VL_SALARIO_ATUAL) AS TOTAL_SALARIO
    FROM TAB_FUNCIONARIO
);

--QUANTIDADE DE FUNCIONARIOS ATIVOS
CREATE OR REPLACE VIEW VW_QTD_FUNC AS
( SELECT COUNT(1) AS QTD_FUNC
    FROM TAB_FUNCIONARIO
   WHERE DT_DEMISSAO IS NULL 
);

--RETORNA SOMENTE O PRIMEIRO NOME DOS FUNCIONARIOS ATIVOS
CREATE OR REPLACE VIEW VW_NOME_FUNC AS
( SELECT SUBSTR(NOME, 0, INSTR(NOME, ' ') -1) AS PRIMEIRO_NOME_FUNC
    FROM TAB_FUNCIONARIO
   WHERE DT_DEMISSAO IS NULL 
);

SELECT * FROM VW_USUARIO_ATIVO;

SELECT * FROM VW_TOTAL_SALARIO;

SELECT * FROM VW_QTD_FUNC;

SELECT * FROM VW_NOME_FUNC;